### PR TITLE
Fix crystal on layout

### PR DESCRIPTION
**Pull request by villaseca**
Connected to #6 and #10

### CODE REVIEW

**Comment by villaseca** [comment]
Also connected to #7, now there is no need to order it with 2oz.

**Comment by villaseca** [comment]
Fixed #9

**Comment by lifeeth** [comment]
screen shot 2016-09-19 at 8 51 19 pm

Looks good - But is the ERC passing for this bit? Maybe worth it to keep more space?

**Comment by villaseca** [comment]
@lifeeth it passes, will add some extra space just to be sure.

**Comment by lifeeth** [comment]
Sounds good!

**Comment by lifeeth** [comment]
LGTM

**Pull request merged**
